### ISSUE TITLE
About status of the project

### ISSUE THREAD

**Issue by rtxa** [madeso/genesis3d#1]
Hi, I wonder what's the current status of the project. I just started a project to convert automatically images from a folder to .TXL texture package, and a C++ wrapper would be really useful. I’ve looked into some of the headers files and I think they're great, but of course they're missing the implementation.

**Comment by madeso** [comment]
The project is more or less complete. You can generate doxygen and read the comments. As stated in the readme the goal was never to compile and run it, just admiring the design. The actual features are less interesting due to it being 25 years old at this point.

If you want to compile and run the code I suggest you get the official sources https://www.genesis3d.com/

**Comment by rtxa** [comment]
Sounds weird "just admiring the design" but okay. I'm just trying to give a little more life to the engine with more simpler interfaces to interact.
